	#define __NEED_INITIALISATION_EXTERNS
	#include "sm16703p-modulator.inc"

	radix decimal

.sm16703pmodulator code
	global rgbLedsModulatorInitialise
	global sm16703pModulatorInitialise

rgbLedsModulatorInitialise:
sm16703pModulatorInitialise:
	pagesel _sm16703pModulatorInitialiseUart1
	call _sm16703pModulatorInitialiseUart1

	pagesel _sm16703pModulatorInitialiseClc4AsByteSynchronisedReset
	call _sm16703pModulatorInitialiseClc4AsByteSynchronisedReset

	pagesel _sm16703pModulatorInitialiseClc1AsModulatedOutput
	call _sm16703pModulatorInitialiseClc1AsModulatedOutput

	pagesel _sm16703pModulatorInitialisePwm3AsLongDutyCycleForOnes
	call _sm16703pModulatorInitialisePwm3AsLongDutyCycleForOnes

	pagesel _sm16703pModulatorInitialisePwm4AsShortDutyCycleForZeroes
	call _sm16703pModulatorInitialisePwm4AsShortDutyCycleForZeroes

	pagesel _sm16703pModulatorInitialiseTimer2ForPwm
	call _sm16703pModulatorInitialiseTimer2ForPwm

	return

	end
