%.o: %.asm
	$(AS) $(ASARGS) -o $@ $<

%.pp.o: %.asm
	cat $< | sed "s/{{FIRMWARE_VER}}/$(FIRMWARE_VERSION)/g" > "`basename $< .asm`.pp.asm"
	$(AS) $(ASARGS) -o $@ "`basename $< .asm`.pp.asm"

%.a: FORCE
	$(MAKE) -C `basename $@ .a` all

FORCE:
