#include <xc.h>

#pragma config "FEXTOSC=OFF"
#pragma config "RSTOSC=HFINT32"
#pragma config "CLKOUTEN=OFF"
#pragma config "CSWEN=OFF"
#pragma config "FCMEN=OFF"
#pragma config "MCLRE=ON"
#pragma config "PWRTE=ON"
#pragma config "LPBOREN=OFF"
#pragma config "BOREN=OFF"
#pragma config "BORV=LO"
#pragma config "ZCD=OFF"
#pragma config "PPS1WAY=OFF"
#pragma config "STVREN=ON"
#pragma config "WDTE=NSLEEP"
#pragma config "WDTCCS=HFINTOSC"
#pragma config "WDTCWS=WDTCWS_6"
#pragma config "WDTCPS=WDTCPS_4"
#pragma config "BBEN=OFF"
#pragma config "SAFEN=ON"
#pragma config "WRTAPP=ON"
#pragma config "WRTB=ON"
#pragma config "WRTC=ON"
#pragma config "WRTSAF=OFF"
#pragma config "LVP=ON"
#pragma config "CP=OFF"
