PP_SED=sed "s/{{FIRMWARE_VERSION}}/$(FIRMWARE_VERSION)/g"

%.pp.o: %.pp.asm
	cat "$<" | $(PP_SED) > "`basename "$@" .pp.o`".asm
	$(AS) $(ASARGS) -o "$@" "`basename "$@" .pp.o`".asm

%.o: %.asm
	$(AS) $(ASARGS) -o "$@" "$<"

%.inc: %.pp.inc
	cat "$<" | $(PP_SED) > "$@"

%.a: FORCE
	$(MAKE) -C `basename "$@" .a` all

FORCE:
